from pydantic import BaseModel
from typing import Optional

quotequote =quotequotequotequote
quotequotequote
quote
quote
quote
quote
quote
quotequote
quote
quote
quotequote
quote
quote
quote
quote
quote
quote
quotequote
quote
quotequotequote
quote
quotequotequotequotequote
quote
quote
quotequotequote
quotequotequote
quotequotequote
quote
quotequotequotequotequotequotequote
quotequotequotequotequotequotequote
quotequotequotequotequotequotequotequotequotequotequotequotequotequote
quotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequote
quotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequote
quotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequote
quotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequote
quotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequote
quotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequote
quotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequote
quotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequotequote